/*
 * WinHTTP probe / stub — instrumentation and controlled response injection.
 *
 * Two jobs, both read-only against Capcom unless explicitly told otherwise:
 *
 *  1. CAPTURE. Log the game's backend conversation — hosts, verbs, paths,
 *     status codes, and (for Capcom hosts, or all hosts under capture_all) the
 *     request and response bodies. This is how the auth exchange on
 *     mtm.rebe.capcom.com/v1/steam-steam/sign was read: a 401 with body
 *     {"error":{"code":269625600,"message":"Ticket decrypt error"}}.
 *
 *  2. STUB. Answer a configured request with a synthetic 200 + body without ever
 *     talking to Capcom, to learn whether the game will proceed past the auth
 *     gate at all. If a faked /sign lets it reach PlayFab / Party init, the only
 *     thing between here and private-server co-op is a transport shim, not a
 *     cryptographic wall. If Denuvo re-checks the token and the game stalls
 *     anyway, even that route is closed. The capture then shows exactly what it
 *     tried next.
 *
 * Everything in (2) is off unless librarian_http.ini beside this DLL turns it
 * on, so an ordinary launch is a pure pass-through. The genuine System32 library
 * must sit beside this one as winhttp_o.dll.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <winhttp.h>
#include <tlhelp32.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

/* Generated by generate.js: one /EXPORT: forwarder per name we do not implement. */
#include "forwards.h"

#define ORIGINAL_DLL  L"winhttp_o.dll"
#define LOG_NAME      "librarian_http.log"
#define INI_NAME      "librarian_http.ini"

static HMODULE g_original;
static CRITICAL_SECTION g_lock;
static volatile LONG g_lock_ready;
static char g_dir[MAX_PATH];        /* folder this DLL lives in, with trailing \ */
static WINHTTP_STATUS_CALLBACK g_app_cb;   /* the game's async completion callback */

/* ─── config (librarian_http.ini) ─────────────────────────────────────── */

static int  g_capture_all;          /* dump bodies for every host, not just capcom */
static char g_fake_urls[1024];      /* comma-separated path substrings to fake */
static char *g_fake_body;           /* synthetic 200 body */
static DWORD g_fake_len;
static int  g_dump_now;             /* dump decrypted code/data sections after a fake /sign */
static volatile LONG g_dumped;
static int  g_hwbp;                 /* arm HW breakpoints at the parse addresses after fake /sign */
static int  g_databp;               /* set a data breakpoint on the served body to find the reader */
static void *g_databp_addr;         /* the game's response buffer we served into */
static volatile LONG g_databp_seen;
static volatile LONG g_databp_addr_armed;
/* Trap the extractor call site to scan the response object it searches. */
static const DWORD g_bp_rva[4] = { 0xa75a0be, 0, 0, 0 };
static const char *g_bp_name[4] = { "extract-call", "", "", "" };
static void *g_bp_addr[4];
static volatile LONG g_bp_seen[4];
static ULONGLONG g_ini_mtime;       /* reload the ini only when it changes */

/*
 * keycap: recover the /sign response schema from ground truth. The generic JSON
 * member extractor lives at rva 0xb4876b0 and takes the key in r8 (proven: the
 * consumer call site passes "rebe_token" in r8). The /sign parse is synchronous
 * on the thread that read the body, so we arm an exec breakpoint on the extractor
 * ENTRY on that one thread only (arming all threads would trap this hot function
 * process-wide) and log every key it searches for during the parse window. The
 * sequence of keys IS the schema.
 */
static int  g_keycap;                       /* ini: capture parser key lookups */
static int  g_no_real_recv;                 /* ini: pure-synthetic /sign (skip real receive) */
static const DWORD g_keycap_rva = 0xb4876b0;/* generic json member extractor entry */
static void *g_keycap_addr;
static volatile DWORD g_sign_tid;           /* thread that served the fake /sign body */
static volatile LONG  g_keycap_seen;

static void probe_log(const char *fmt, ...);   /* defined below */
static const char *dir_path(void);             /* defined below */

/* Arm DR0 at base+0xa75a0b1 on the current thread (sync /sign parses on the
 * same thread that read the body). The VEH logs if it is reached. */
static void set_drs(CONTEXT *c)
{
    if (g_databp) {
        /* DR0 = data read/write breakpoint (RW0=11, LEN0=11 -> 8 bytes) on the body */
        c->Dr0 = (DWORD64)(ULONG_PTR)g_databp_addr;
        c->Dr7 = (c->Dr7 & ~(DWORD64)0xffffffff) | 0x1 | (0x3ULL << 16) | (0x3ULL << 18);
        return;
    }
    c->Dr0 = (DWORD64)(ULONG_PTR)g_bp_addr[0];
    c->Dr1 = (DWORD64)(ULONG_PTR)g_bp_addr[1];
    c->Dr2 = (DWORD64)(ULONG_PTR)g_bp_addr[2];
    c->Dr3 = (DWORD64)(ULONG_PTR)g_bp_addr[3];
    /* enable L0..L3 (bits 0,2,4,6 = 0x55); RW/LEN fields 0 = execute, len 1 */
    c->Dr7 = (c->Dr7 & ~(DWORD64)0xffffffff) | 0x55;
}
static void arm_all_threads(void)
{
    CONTEXT c; memset(&c, 0, sizeof c); c.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    HANDLE th = GetCurrentThread();
    if (GetThreadContext(th, &c)) { set_drs(&c); c.ContextFlags = CONTEXT_DEBUG_REGISTERS; SetThreadContext(th, &c); }
    DWORD me = GetCurrentThreadId(), pid = GetCurrentProcessId(), armed = 0;
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
    if (snap != INVALID_HANDLE_VALUE) {
        THREADENTRY32 te; te.dwSize = sizeof te;
        if (Thread32First(snap, &te)) do {
            if (te.th32OwnerProcessID != pid || te.th32ThreadID == me) continue;
            HANDLE h = OpenThread(THREAD_SUSPEND_RESUME | THREAD_GET_CONTEXT | THREAD_SET_CONTEXT, FALSE, te.th32ThreadID);
            if (!h) continue;
            SuspendThread(h);
            CONTEXT tc; memset(&tc, 0, sizeof tc); tc.ContextFlags = CONTEXT_DEBUG_REGISTERS;
            if (GetThreadContext(h, &tc)) { set_drs(&tc); tc.ContextFlags = CONTEXT_DEBUG_REGISTERS; if (SetThreadContext(h, &tc)) armed++; }
            ResumeThread(h);
            CloseHandle(h);
        } while (Thread32Next(snap, &te));
        CloseHandle(snap);
    }
    probe_log("%s armed on current + %lu other threads", g_databp ? "DATABP" : "HWBP(4)", armed);
}
static void arm_hwbp(void)
{
    BYTE *base = (BYTE *)GetModuleHandleW(NULL);
    if (!base) return;
    for (int i = 0; i < 4; i++) g_bp_addr[i] = base + g_bp_rva[i];
    arm_all_threads();
}

/* Arm DR3 (execute) at the json extractor entry on the CURRENT thread only. */
static void arm_keycap_current(void)
{
    BYTE *base = (BYTE *)GetModuleHandleW(NULL);
    if (!base) return;
    g_keycap_addr = base + g_keycap_rva;
    CONTEXT c; memset(&c, 0, sizeof c); c.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    HANDLE th = GetCurrentThread();
    if (!GetThreadContext(th, &c)) return;
    c.Dr3 = (DWORD64)(ULONG_PTR)g_keycap_addr;
    /* enable L3 (bit 6); RW3/LEN3 = 00 -> execute, 1 byte */
    c.Dr7 = (c.Dr7 & ~((DWORD64)0x3 << 6)) | ((DWORD64)0x1 << 6);
    c.Dr7 &= ~((DWORD64)0xff << 28);   /* RW3/LEN3 fields = 0 (execute) */
    c.ContextFlags = CONTEXT_DEBUG_REGISTERS;
    SetThreadContext(th, &c);
    probe_log("KEYCAP armed DR3 @%p (rva 0x%lx) tid=%lu", g_keycap_addr, g_keycap_rva, GetCurrentThreadId());
}

static void probe_log(const char *fmt, ...);   /* defined below */
static const char *dir_path(void);             /* defined below */

/*
 * Dump decrypted PE sections from our own process, a few seconds after the
 * /sign parse has run (so Denuvo has decrypted that code path). Offline analysis
 * then finds the parser by the RIP-relative LEAs that reference the rebe key
 * strings. Sections of interest: .data holds the code here (Denuvo-renamed,
 * executable), and .sdata/.rodata/.srdata hold the string literals.
 */
static DWORD WINAPI dump_worker(LPVOID param)
{
    (void)param;
    Sleep(5000);
    const char *dir = dir_path();
    if (!dir) return 0;
    BYTE *base = (BYTE *)GetModuleHandleW(NULL);
    if (!base) { probe_log("DUMP: no module base"); return 0; }
    IMAGE_DOS_HEADER *dos = (IMAGE_DOS_HEADER *)base;
    IMAGE_NT_HEADERS *nt = (IMAGE_NT_HEADERS *)(base + dos->e_lfanew);
    IMAGE_SECTION_HEADER *sec = IMAGE_FIRST_SECTION(nt);
    probe_log("DUMP begin base=%p sections=%u", (void *)base, nt->FileHeader.NumberOfSections);
    for (int i = 0; i < nt->FileHeader.NumberOfSections; i++) {
        char nm[9] = {0}; memcpy(nm, sec[i].Name, 8);
        if (strcmp(nm, ".data") && strcmp(nm, ".sdata") && strcmp(nm, ".rodata") && strcmp(nm, ".srdata") && strcmp(nm, ".udata")) continue;
        DWORD rva = sec[i].VirtualAddress, sz = sec[i].Misc.VirtualSize;
        char path[MAX_PATH];
        _snprintf(path, sizeof path - 1, "%slibrarian_dump_%s.bin", dir, nm[0] == '.' ? nm + 1 : nm);
        path[sizeof path - 1] = 0;
        HANDLE h = CreateFileA(path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
        if (h == INVALID_HANDLE_VALUE) { probe_log("DUMP %s: open failed %lu", nm, GetLastError()); continue; }
        DWORD total = 0;
        while (total < sz) {
            DWORD chunk = sz - total > (4u << 20) ? (4u << 20) : sz - total, wr = 0;
            /* guard against non-committed pages so a bad read can't kill the game */
            if (IsBadReadPtr(base + rva + total, chunk)) { total += chunk; continue; }
            if (!WriteFile(h, base + rva + total, chunk, &wr, NULL) || wr != chunk) break;
            total += wr;
        }
        CloseHandle(h);
        probe_log("DUMP %s rva=0x%lX vsize=0x%lX wrote=0x%lX", nm, rva, sz, total);
    }
    probe_log("DUMP done");
    return 0;
}

static void probe_log(const char *fmt, ...);   /* defined below; used by load_config */

/*
 * Catch the JSON parse exception to learn the exact schema the game wants.
 *
 * The /sign response is parsed by native C++ (nlohmann-style); a wrong shape
 * throws a C++ exception whose what() names the offending key or type
 * ("[json.exception.out_of_range.403] key 'gcp_token' not found"). This DLL is
 * mapped in the game process, so a vectored handler can read that message — only
 * in a short window right after we serve the faked /sign body, and it never
 * swallows the exception (always CONTINUE_SEARCH).
 */
static volatile ULONGLONG g_veh_deadline;   /* capture only briefly after a fake /sign */
static volatile LONG      g_veh_hits;

static volatile LONG g_veh_seen;   /* total C++ throws the VEH ever observed */

static LONG CALLBACK cpp_exc_veh(PEXCEPTION_POINTERS ep)
{
    /* Hardware-breakpoint traps: which JWT-claim read sites does the parse reach? */
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_SINGLE_STEP) {
        /* keycap: log the key (r8) the json extractor is searching for, on the
         * /sign parse thread only. DR3 (Dr6 bit 3). */
        if (g_keycap && g_keycap_addr && (void *)ep->ContextRecord->Rip == g_keycap_addr) {
            if (GetCurrentThreadId() == g_sign_tid && g_keycap_seen < 200) {
                ULONG64 k = ep->ContextRecord->R8;
                char key[64]; key[0] = 0;
                if (k > 0x10000 && !IsBadReadPtr((void *)k, 2)) {
                    int n = 0; for (; n < 62; n++) { if (IsBadReadPtr((char *)k + n, 1)) break; char ch = ((char *)k)[n]; if (ch < 0x20 || ch > 0x7e) break; key[n] = ch; } key[n] = 0;
                }
                /* also try rdx as key, in case the convention differs */
                ULONG64 k2 = ep->ContextRecord->Rdx; char key2[64]; key2[0] = 0;
                if (k2 > 0x10000 && !IsBadReadPtr((void *)k2, 2)) {
                    int n = 0; for (; n < 62; n++) { if (IsBadReadPtr((char *)k2 + n, 1)) break; char ch = ((char *)k2)[n]; if (ch < 0x20 || ch > 0x7e) break; key2[n] = ch; } key2[n] = 0;
                }
                probe_log("KEYCAP r8=\"%s\" rdx=\"%s\"", key, key2);
                InterlockedIncrement(&g_keycap_seen);
            }
            ep->ContextRecord->EFlags |= 0x10000;   /* RF: run this instr once w/o re-trap */
            return EXCEPTION_CONTINUE_EXECUTION;
        }
        /* Data breakpoint: who reads the body buffer we served? */
        if (g_databp && (ep->ContextRecord->Dr6 & 0x1)) {
            void *rip = (void *)ep->ContextRecord->Rip;
            if (g_databp_seen < 8) {
                BYTE *base = (BYTE *)GetModuleHandleW(NULL);
                probe_log("DATABP body read @rip=%p (base+0x%llx)", rip, (ULONG64)((BYTE *)rip - base));
            }
            InterlockedIncrement(&g_databp_seen);
            ep->ContextRecord->Dr6 = 0;
            if (g_databp_seen > 8) ep->ContextRecord->Dr7 &= ~(DWORD64)0x1;   /* stop after samples */
            return EXCEPTION_CONTINUE_EXECUTION;
        }
        void *rip = (void *)ep->ContextRecord->Rip;
        for (int i = 0; i < 4; i++) {
            if (g_bp_addr[i] && rip == g_bp_addr[i]) {
                CONTEXT *c = ep->ContextRecord;
                if (g_bp_seen[i] < 1) {
                    probe_log("HWBP[%s] rdx=%llx r14=%llx", g_bp_name[i], c->Rdx, c->R14);
                    /* Scan the response object + nearby heap for ASCII strings, and
                     * chase 2 levels of pointers, to see what the parser holds. */
                    ULONG64 roots[2] = { c->Rdx, c->R14 };
                    for (int r = 0; r < 2; r++) {
                        ULONG64 basep = roots[r];
                        for (ULONG64 off = 0; off < 0x120; off += 8) {
                            if (IsBadReadPtr((void *)(basep + off), 8)) continue;
                            ULONG64 p = *(ULONG64 *)(basep + off);
                            /* inline string at basep+off? */
                            char *cp = (char *)(basep + off);
                            if (!IsBadReadPtr(cp, 4) && cp[0] >= 0x20 && cp[0] <= 0x7e && cp[1] >= 0x20 && cp[1] <= 0x7e) {
                                char t[48]; int n = 0; for (; n < 46; n++) { if (IsBadReadPtr(cp + n, 1)) break; char ch = cp[n]; if (ch < 0x20 || ch > 0x7e) break; t[n] = ch; } t[n] = 0;
                                if (n >= 4) probe_log("   [%llx+%llx] inline \"%s\"", basep, off, t);
                            }
                            /* pointed-to string? */
                            if (p > 0x10000 && !IsBadReadPtr((void *)p, 4)) {
                                char *pp = (char *)p; char t[48]; int n = 0;
                                for (; n < 46; n++) { if (IsBadReadPtr(pp + n, 1)) break; char ch = pp[n]; if (ch < 0x20 || ch > 0x7e) break; t[n] = ch; } t[n] = 0;
                                if (n >= 4) probe_log("   [%llx+%llx]->\"%s\"", basep, off, t);
                            }
                        }
                    }
                    /* read candidate response strings: pointer, and one/two derefs */
                    ULONG64 regs[3] = { c->Rdx, c->R14, c->Rcx };
                    const char *rn[3] = { "rdx", "r14", "rcx" };
                    for (int k = 0; k < 3; k++) {
                        ULONG64 p = regs[k];
                        for (int lvl = 0; lvl < 3 && p; lvl++) {
                            if (!IsBadReadPtr((void *)p, 16)) {
                                char t[160]; int n = 0;
                                for (; n < 158; n++) { char ch = ((char *)p)[n]; if (IsBadReadPtr((char *)p + n, 1)) break; if (!ch) break; if (ch < 0x20 || ch > 0x7e) break; t[n] = ch; }
                                t[n] = 0;
                                if (n >= 3) { probe_log("   %s%*slvl%d @%llx = \"%s\"", rn[k], lvl, "", lvl, p, t); break; }
                            }
                            p = IsBadReadPtr((void *)p, 8) ? 0 : *(ULONG64 *)p;   /* deref */
                        }
                    }
                    /* also log r8 as string (should be the key "rebe_token") */
                    if (!IsBadReadPtr((void *)c->R8, 11)) probe_log("   r8key = \"%.10s\"", (char *)c->R8);
                }
                InterlockedIncrement(&g_bp_seen[i]);
                c->EFlags |= 0x10000;   /* RF: run this instr once w/o re-trap */
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }
        return EXCEPTION_CONTINUE_SEARCH;
    }
    if (ep->ExceptionRecord->ExceptionCode != 0xE06D7363) return EXCEPTION_CONTINUE_SEARCH; /* MSVC C++ throw */
    /* Liveness proof: log the first few C++ throws seen anytime, to tell a
     * non-throwing parser apart from a VEH that Denuvo has stripped. */
    LONG seen = InterlockedIncrement(&g_veh_seen);
    if (seen <= 5) probe_log("VEH alive: C++ throw #%ld observed", seen);
    if (GetTickCount64() > g_veh_deadline) return EXCEPTION_CONTINUE_SEARCH;
    if (g_veh_hits > 8) return EXCEPTION_CONTINUE_SEARCH;
    __try {
        EXCEPTION_RECORD *er = ep->ExceptionRecord;
        char *obj  = (er->NumberParameters >= 2) ? (char *)er->ExceptionInformation[1] : NULL;

        /* RTTI type name via the MSVC x64 throw ABI: params[2]=ThrowInfo(ptr),
         * params[3]=image base; all inner pointers are RVAs off that base. */
        char tname[160]; tname[0] = '\0';
        if (er->NumberParameters >= 4) {
            char *base = (char *)er->ExceptionInformation[3];
            char *ti   = (char *)er->ExceptionInformation[2];
            if (base && ti && !IsBadReadPtr(ti + 0x0C, 4)) {
                char *cta = base + *(int *)(ti + 0x0C);            /* CatchableTypeArray */
                if (!IsBadReadPtr(cta, 8) && *(int *)cta > 0) {
                    char *ct = base + *(int *)(cta + 4);           /* CatchableType[0] */
                    if (!IsBadReadPtr(ct + 4, 4)) {
                        char *td = base + *(int *)(ct + 4);        /* TypeDescriptor */
                        char *nm = td + 0x10;                      /* mangled name */
                        int i = 0; for (; i < 158; i++) { if (IsBadReadPtr(nm + i, 1)) break; char c = nm[i]; if (!c) break; if (c < 0x20 || c > 0x7e) break; tname[i] = c; }
                        tname[i] = '\0';
                    }
                }
            }
        }

        /* what() text: scan the object's slots (and one deref deeper) for a message. */
        char best[240]; best[0] = '\0';
        for (int o = 0; obj && o <= 0x60 && !best[0]; o += 8) {
            if (IsBadReadPtr(obj + o, sizeof(void *))) continue;
            char *p = *(char **)(obj + o);
            for (int lvl = 0; lvl < 2 && p && !best[0]; lvl++) {
                if (!IsBadReadPtr(p, 8)) {
                    int i = 0; char tmp[240];
                    for (; i < 238; i++) { if (IsBadReadPtr(p + i, 1)) break; char c = p[i]; if (!c) break; if (c < 0x20 || c > 0x7e) break; tmp[i] = c; }
                    tmp[i] = '\0';
                    if (i > 6 && (strstr(tmp, "json") || strstr(tmp, "key '") || strstr(tmp, "type must") || strstr(tmp, "parse error"))) { strncpy(best, tmp, sizeof best - 1); best[sizeof best - 1] = '\0'; break; }
                    if (!IsBadReadPtr(p, sizeof(void *))) p = *(char **)p; else p = 0;
                } else p = 0;
            }
        }
        probe_log("CPP-EXC type=%s what=%s", tname[0] ? tname : "?", best[0] ? best : "(none)");
        InterlockedIncrement(&g_veh_hits);
    } __except (EXCEPTION_EXECUTE_HANDLER) { /* our own fault while probing — ignore */ }
    return EXCEPTION_CONTINUE_SEARCH;   /* never interfere with the game's handling */
}

static const char *dir_path(void)
{
    if (g_dir[0]) return g_dir;
    HMODULE self = NULL;
    GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                       (LPCWSTR)(void *)&dir_path, &self);
    char buf[MAX_PATH];
    DWORD n = GetModuleFileNameA(self, buf, sizeof buf);
    if (n == 0 || n >= sizeof buf) return NULL;
    char *slash = strrchr(buf, '\\');
    if (!slash) return NULL;
    *(slash + 1) = '\0';
    strcpy(g_dir, buf);
    return g_dir;
}

/* Trim leading/trailing ASCII whitespace in place. */
static char *trim(char *s)
{
    while (*s == ' ' || *s == '\t' || *s == '\r' || *s == '\n') s++;
    char *e = s + strlen(s);
    while (e > s && (e[-1] == ' ' || e[-1] == '\t' || e[-1] == '\r' || e[-1] == '\n')) *--e = '\0';
    return s;
}

/*
 * Re-read the ini whenever it changes on disk.
 *
 * The game re-attempts authorization every few minutes on its own, so with a
 * hot-reloading config the response body can be iterated by editing the ini and
 * waiting for the next attempt — no relaunch, which matters because the
 * anti-tamper hypervisor makes the game process impossible to close on demand.
 */
static void load_config(void)
{
    const char *dir = dir_path();
    if (!dir) return;
    char path[MAX_PATH];
    if (strlen(dir) + strlen(INI_NAME) >= sizeof path) return;
    strcpy(path, dir); strcat(path, INI_NAME);

    WIN32_FILE_ATTRIBUTE_DATA fad;
    if (!GetFileAttributesExA(path, GetFileExInfoStandard, &fad)) return;
    ULONGLONG mt = ((ULONGLONG)fad.ftLastWriteTime.dwHighDateTime << 32) | fad.ftLastWriteTime.dwLowDateTime;
    if (mt == g_ini_mtime && g_fake_body) return;        /* unchanged since last read */

    FILE *f = fopen(path, "rb");
    if (!f) return;

    int   cap_all = 0;
    char  urls[1024] = "";
    char *body = NULL;
    DWORD blen = 0;
    char  line[8192];                                    /* bodies can be a couple of KB */
    while (fgets(line, sizeof line, f)) {
        char *s = trim(line);
        if (!*s || *s == '#' || *s == ';' || *s == '[') continue;
        char *eq = strchr(s, '=');
        if (!eq) continue;
        *eq = '\0';
        char *key = trim(s), *val = trim(eq + 1);
        if (!strcmp(key, "capture_all"))   cap_all = atoi(val) != 0;
        else if (!strcmp(key, "dump_now"))  g_dump_now = atoi(val) != 0;
        else if (!strcmp(key, "hwbp"))      g_hwbp = atoi(val) != 0;
        else if (!strcmp(key, "databp"))    g_databp = atoi(val) != 0;
        else if (!strcmp(key, "keycap"))    g_keycap = atoi(val) != 0;
        else if (!strcmp(key, "no_real_recv")) g_no_real_recv = atoi(val) != 0;
        else if (!strcmp(key, "fake_urls")) { strncpy(urls, val, sizeof urls - 1); urls[sizeof urls - 1] = '\0'; }
        else if (!strcmp(key, "fake_body")) {
            size_t n = strlen(val);
            char *b = (char *)malloc(n + 1);
            if (b) { memcpy(b, val, n + 1); free(body); body = b; blen = (DWORD)n; }
        }
    }
    fclose(f);
    if (!body) { body = _strdup("{}"); blen = 2; }

    EnterCriticalSection(&g_lock);
    char *old = g_fake_body;
    g_capture_all = cap_all;
    strncpy(g_fake_urls, urls, sizeof g_fake_urls - 1); g_fake_urls[sizeof g_fake_urls - 1] = '\0';
    g_fake_body = body; g_fake_len = blen; g_ini_mtime = mt;
    LeaveCriticalSection(&g_lock);
    free(old);
    probe_log("config (re)loaded: capture_all=%d fake_urls=%s body=%lu bytes", cap_all, g_fake_urls, blen);
}

/* ─── logging ─────────────────────────────────────────────────────────── */

static void probe_log(const char *fmt, ...)
{
    const char *dir = dir_path();
    if (!dir) return;
    char path[MAX_PATH];
    if (strlen(dir) + strlen(LOG_NAME) >= sizeof path) return;
    strcpy(path, dir); strcat(path, LOG_NAME);

    EnterCriticalSection(&g_lock);
    FILE *f = fopen(path, "a");
    if (f) {
        SYSTEMTIME t; GetLocalTime(&t);
        fprintf(f, "[%02u:%02u:%02u.%03u] ", t.wHour, t.wMinute, t.wSecond, t.wMilliseconds);
        va_list ap; va_start(ap, fmt); vfprintf(f, fmt, ap); va_end(ap);
        fputc('\n', f);
        fclose(f);
    }
    LeaveCriticalSection(&g_lock);
}

/* ─── handle → label table (for attribution) ──────────────────────────── */

#define SLOTS 64
static struct { HINTERNET h; char label[320]; } g_slots[SLOTS];
static unsigned g_next;

static void remember(HINTERNET h, const char *label)
{
    if (!h) return;
    EnterCriticalSection(&g_lock);
    unsigned i = g_next++ % SLOTS;
    g_slots[i].h = h;
    strncpy(g_slots[i].label, label, sizeof g_slots[i].label - 1);
    g_slots[i].label[sizeof g_slots[i].label - 1] = '\0';
    LeaveCriticalSection(&g_lock);
}

static void recall(HINTERNET h, char *out, size_t cap)
{
    out[0] = '\0';
    EnterCriticalSection(&g_lock);
    /*
     * Newest first. WinHTTP recycles handle values, so the same HINTERNET can
     * appear in the ring twice — once for a closed request and once for the live
     * one. Scanning oldest-first returned the stale label and mis-attributed
     * every header, body and status (and, worse, defeated should_fake). Walking
     * back from the most recent write returns the label for the request that is
     * actually in flight.
     */
    for (unsigned k = 1; k <= SLOTS; k++) {
        unsigned i = (g_next - k) % SLOTS;
        if (g_slots[i].h == h) { strncpy(out, g_slots[i].label, cap - 1); out[cap - 1] = '\0'; break; }
    }
    LeaveCriticalSection(&g_lock);
    if (!out[0]) strncpy(out, "(unknown handle)", cap - 1);
}

/*
 * Requests marked at open time to receive a synthetic response.
 *
 * The fake decision is made in WinHttpOpenRequest, where the object path is a
 * direct argument and cannot be confused by handle reuse — never from a recalled
 * label. A fresh open on a recycled handle clears any stale mark first.
 */
#define PENDING 16
static HINTERNET g_pending[PENDING];

static void pending_mark(HINTERNET h, int on)
{
    EnterCriticalSection(&g_lock);
    if (on) {
        int s = -1;
        for (int i = 0; i < PENDING; i++) if (!g_pending[i]) { s = i; break; }
        if (s < 0) s = 0;
        g_pending[s] = h;
    } else {
        for (int i = 0; i < PENDING; i++) if (g_pending[i] == h) g_pending[i] = NULL;
    }
    LeaveCriticalSection(&g_lock);
}

static int pending_is(HINTERNET h)
{
    int found = 0;
    EnterCriticalSection(&g_lock);
    for (int i = 0; i < PENDING; i++) if (g_pending[i] == h) { found = 1; break; }
    LeaveCriticalSection(&g_lock);
    return found;
}

/* ─── faked-request table (stub mode) ─────────────────────────────────── */

#define FAKES 16
static struct { HINTERNET h; DWORD off; } g_fakes[FAKES];

static void fake_register(HINTERNET h)
{
    EnterCriticalSection(&g_lock);
    int slot = -1;
    for (int i = 0; i < FAKES; i++) if (!g_fakes[i].h) { slot = i; break; }
    if (slot < 0) slot = 0;                 /* overwrite oldest-ish; fakes are short-lived */
    g_fakes[slot].h = h;
    g_fakes[slot].off = 0;
    LeaveCriticalSection(&g_lock);
}

/* Returns the fake slot index for h, or -1. Caller holds no lock. */
static int fake_slot(HINTERNET h)
{
    int found = -1;
    EnterCriticalSection(&g_lock);
    for (int i = 0; i < FAKES; i++) if (g_fakes[i].h == h) { found = i; break; }
    LeaveCriticalSection(&g_lock);
    return found;
}

/* Does this label match any configured fake substring? */
static int should_fake(const char *label)
{
    if (!g_fake_urls[0]) return 0;
    char list[1024];
    strncpy(list, g_fake_urls, sizeof list - 1);
    list[sizeof list - 1] = '\0';
    for (char *tok = strtok(list, ","); tok; tok = strtok(NULL, ",")) {
        char *t = trim(tok);
        if (*t && strstr(label, t)) return 1;
    }
    return 0;
}

/* ─── forwarding + helpers ────────────────────────────────────────────── */

static FARPROC resolve(const char *name)
{
    if (!g_original) {
        HMODULE h = GetModuleHandleW(ORIGINAL_DLL);
        if (!h) h = LoadLibraryW(ORIGINAL_DLL);
        if (!h) { probe_log("FATAL: cannot load %ls", ORIGINAL_DLL); return NULL; }
        g_original = h;
    }
    FARPROC fn = GetProcAddress(g_original, name);
    if (!fn) probe_log("FATAL: %s missing from %ls", name, ORIGINAL_DLL);
    return fn;
}

static void narrow(const wchar_t *w, char *out, size_t cap)
{
    if (!w) { strncpy(out, "(null)", cap - 1); out[cap - 1] = '\0'; return; }
    int n = WideCharToMultiByte(CP_ACP, 0, w, -1, out, (int)cap, "?", NULL);
    if (n <= 0) { strncpy(out, "(unconvertible)", cap - 1); out[cap - 1] = '\0'; }
}

static void narrow_n(const wchar_t *w, DWORD wlen, char *out, size_t cap)
{
    if (!w) { strncpy(out, "(null)", cap - 1); out[cap - 1] = '\0'; return; }
    int cch = (wlen == (DWORD)-1L) ? -1 : (int)wlen;
    int n = WideCharToMultiByte(CP_ACP, 0, w, cch, out, (int)cap - 1, "?", NULL);
    if (n < 0) n = 0;
    out[n] = '\0';
}

static int should_capture(const char *label)
{
    if (g_capture_all) return 1;
    for (const char *p = label; *p; p++)
        if ((*p == 'c' || *p == 'C') && _strnicmp(p, "capcom", 6) == 0) return 1;
    return 0;
}

static void log_bytes(const char *tag, const char *label, const void *buf, DWORD len)
{
    if (!buf || !len) return;
    DWORD cap = len > 2048 ? 2048 : len;
    char *tmp = (char *)malloc(cap + 1);
    if (!tmp) return;
    const unsigned char *s = (const unsigned char *)buf;
    for (DWORD i = 0; i < cap; i++) {
        unsigned char c = s[i];
        tmp[i] = (c == '\n' || c == '\r') ? ' ' : (c >= 0x20 && c <= 0x7e) ? (char)c : '.';
    }
    tmp[cap] = '\0';
    probe_log("  %s [%s] (%lu bytes) %s%s", tag, label, len, tmp, len > cap ? " ...(truncated)" : "");
    free(tmp);
}

/* ─── connect / open (attribution) ────────────────────────────────────── */

typedef HINTERNET (WINAPI *fn_connect)(HINTERNET, LPCWSTR, INTERNET_PORT, DWORD);
typedef HINTERNET (WINAPI *fn_open)(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR *, DWORD);

__declspec(dllexport)
HINTERNET WINAPI WinHttpConnect(HINTERNET session, LPCWSTR server, INTERNET_PORT port, DWORD reserved)
{
    load_config();
    fn_connect fn = (fn_connect)resolve("WinHttpConnect");
    if (!fn) return NULL;
    HINTERNET h = fn(session, server, port, reserved);
    char host[256]; narrow(server, host, sizeof host);
    char label[320]; _snprintf(label, sizeof label - 1, "%s:%u", host, (unsigned)port); label[sizeof label - 1] = '\0';
    remember(h, label);
    probe_log("CONNECT %s", label);
    return h;
}

__declspec(dllexport)
HINTERNET WINAPI WinHttpOpenRequest(HINTERNET connect, LPCWSTR verb, LPCWSTR object,
                                    LPCWSTR version, LPCWSTR referrer, LPCWSTR *acceptTypes, DWORD flags)
{
    fn_open fn = (fn_open)resolve("WinHttpOpenRequest");
    if (!fn) return NULL;
    HINTERNET h = fn(connect, verb, object, version, referrer, acceptTypes, flags);
    char host[320], v[16], obj[256];
    recall(connect, host, sizeof host);
    narrow(verb ? verb : L"GET", v, sizeof v);
    narrow(object, obj, sizeof obj);
    char label[320]; _snprintf(label, sizeof label - 1, "%s %s%s", v, host, obj); label[sizeof label - 1] = '\0';
    remember(h, label);
    probe_log("REQUEST %s", label);

    /* Decide the fake here, from the real object path — never from a recalled label. */
    load_config();
    pending_mark(h, 0);                       /* clear any stale mark on a recycled handle */
    if (should_fake(obj)) { pending_mark(h, 1); probe_log("  STUB: marked to fake -> %s", obj); }
    return h;
}

/* ─── request headers / body capture ──────────────────────────────────── */

typedef BOOL (WINAPI *fn_addhdr)(HINTERNET, LPCWSTR, DWORD, DWORD);
typedef BOOL (WINAPI *fn_send)(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR);
typedef BOOL (WINAPI *fn_write)(HINTERNET, LPCVOID, DWORD, LPDWORD);
typedef BOOL (WINAPI *fn_recv)(HINTERNET, LPVOID);
typedef BOOL (WINAPI *fn_qhdr)(HINTERNET, DWORD, LPCWSTR, LPVOID, LPDWORD, LPDWORD);
typedef BOOL (WINAPI *fn_qavail)(HINTERNET, LPDWORD);
typedef BOOL (WINAPI *fn_read)(HINTERNET, LPVOID, DWORD, LPDWORD);

__declspec(dllexport)
BOOL WINAPI WinHttpAddRequestHeaders(HINTERNET request, LPCWSTR headers, DWORD length, DWORD modifiers)
{
    fn_addhdr fn = (fn_addhdr)resolve("WinHttpAddRequestHeaders");
    if (!fn) return FALSE;
    char label[320]; recall(request, label, sizeof label);
    if (headers && should_capture(label)) {
        char h[2048]; narrow_n(headers, length, h, sizeof h);
        probe_log("  ADD-HEADERS [%s] %s", label, h);
    }
    return fn(request, headers, length, modifiers);
}

__declspec(dllexport)
BOOL WINAPI WinHttpSendRequest(HINTERNET request, LPCWSTR headers, DWORD headersLen,
                               LPVOID optional, DWORD optionalLen, DWORD totalLen, DWORD_PTR context)
{
    fn_send fn = (fn_send)resolve("WinHttpSendRequest");
    if (!fn) return FALSE;
    char label[320]; recall(request, label, sizeof label);
    if (should_capture(label)) {
        if (headers && headersLen) { char h[2048]; narrow_n(headers, headersLen, h, sizeof h); probe_log("  SEND-HEADERS [%s] %s", label, h); }
        if (optional && optionalLen) log_bytes("SEND-BODY", label, optional, optionalLen);
    }
    return fn(request, headers, headersLen, optional, optionalLen, totalLen, context);
}

__declspec(dllexport)
BOOL WINAPI WinHttpWriteData(HINTERNET request, LPCVOID buffer, DWORD toWrite, LPDWORD written)
{
    fn_write fn = (fn_write)resolve("WinHttpWriteData");
    if (!fn) return FALSE;
    char label[320]; recall(request, label, sizeof label);
    if (should_capture(label)) log_bytes("WRITE-BODY", label, buffer, toWrite);
    return fn(request, buffer, toWrite, written);
}

/* ─── response: receive / status / available / read ───────────────────── */

__declspec(dllexport)
BOOL WINAPI WinHttpReceiveResponse(HINTERNET request, LPVOID reserved)
{
    char label[320]; recall(request, label, sizeof label);

    /*
     * Stub: a configured request is answered with a synthetic 200 and never
     * reaches Capcom's response. The request itself already went out at
     * SendRequest (harmless — Capcom's 401 is simply ignored); from here the
     * caller sees only our fabricated status and body.
     */
    if (pending_is(request)) {
        pending_mark(request, 0);
        /*
         * Do NOT call the real receive: it delivers Capcom's real 401 status into
         * the handle, and the rebe layer then treats the request as failed and
         * never parses the body (proven with a data breakpoint: the served buffer
         * is never read). We fully synthesize the 200 instead — every read/query
         * the game makes on this handle is overridden below, so it never touches
         * the real handle state. (Earlier this tripped 0x2EF3; the override set is
         * now complete, so retry the pure-synthetic path.)
         */
        if (!g_no_real_recv) {
            fn_recv rf = (fn_recv)resolve("WinHttpReceiveResponse");
            if (rf) rf(request, reserved);   /* complete the request so the extractor runs */
        }
        fake_register(request);
        probe_log("STUB: faking HTTP 200 for [%s] (%s) body=%lu bytes", label,
                  g_no_real_recv ? "pure synth" : "real recv", g_fake_len);
        return TRUE;
    }

    fn_recv fn = (fn_recv)resolve("WinHttpReceiveResponse");
    if (!fn) return FALSE;
    BOOL ok = fn(request, reserved);
    if (!ok) { probe_log("  -> FAILED (win32 %lu)  %s", GetLastError(), label); return ok; }

    fn_qhdr q = (fn_qhdr)resolve("WinHttpQueryHeaders");
    DWORD status = 0, size = sizeof status;
    if (q && q(request, WINHTTP_QUERY_STATUS_CODE | WINHTTP_QUERY_FLAG_NUMBER,
               WINHTTP_HEADER_NAME_BY_INDEX, &status, &size, WINHTTP_NO_HEADER_INDEX))
        probe_log("  -> HTTP %lu  %s", status, label);
    else
        probe_log("  -> ok, status unavailable  %s", label);
    return ok;
}

__declspec(dllexport)
BOOL WINAPI WinHttpQueryHeaders(HINTERNET request, DWORD infoLevel, LPCWSTR name,
                                LPVOID buffer, LPDWORD bufLen, LPDWORD index)
{
    if (fake_slot(request) >= 0) {
        DWORD base = infoLevel & 0x00FFFFFF;
        int wantNumber = (infoLevel & WINHTTP_QUERY_FLAG_NUMBER) != 0;

        /* Numeric answers: status code and content length. */
        if (wantNumber && (base == WINHTTP_QUERY_STATUS_CODE || base == WINHTTP_QUERY_CONTENT_LENGTH)) {
            DWORD v = (base == WINHTTP_QUERY_STATUS_CODE) ? 200 : g_fake_len;
            if (buffer && bufLen && *bufLen >= sizeof(DWORD)) { *(DWORD *)buffer = v; *bufLen = sizeof(DWORD); return TRUE; }
            if (bufLen) { *bufLen = sizeof(DWORD); SetLastError(ERROR_INSUFFICIENT_BUFFER); return FALSE; }
        }

        /* String answers: build the requested value, then copy with the wide-string convention. */
        const wchar_t *val = NULL;
        wchar_t scratch[512];
        if (base == WINHTTP_QUERY_STATUS_CODE)        val = L"200";
        else if (base == WINHTTP_QUERY_STATUS_TEXT)   val = L"OK";
        else if (base == WINHTTP_QUERY_VERSION)       val = L"HTTP/1.1";
        else if (base == WINHTTP_QUERY_CONTENT_TYPE)  val = L"application/json";
        else if (base == WINHTTP_QUERY_CONTENT_LENGTH) { _snwprintf(scratch, 511, L"%lu", g_fake_len); scratch[511]=0; val = scratch; }
        else if (base == WINHTTP_QUERY_RAW_HEADERS_CRLF) {
            _snwprintf(scratch, 511,
                L"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: %lu\r\n\r\n", g_fake_len);
            scratch[511] = 0; val = scratch;
        }
        if (val) {
            DWORD bytesWithNul = (DWORD)((wcslen(val) + 1) * sizeof(wchar_t));
            if (buffer && bufLen && *bufLen >= bytesWithNul) {
                memcpy(buffer, val, bytesWithNul);
                *bufLen = bytesWithNul - sizeof(wchar_t);   /* success: length excludes the null */
                return TRUE;
            }
            if (bufLen) { *bufLen = bytesWithNul; SetLastError(ERROR_INSUFFICIENT_BUFFER); return FALSE; }
        }

        /*
         * Any other header: fall through to the real library. Because we now let
         * the real response arrive, the handle has genuine headers to serve, so
         * an un-synthesised query still succeeds instead of erroring.
         */
    }
    fn_qhdr fn = (fn_qhdr)resolve("WinHttpQueryHeaders");
    if (!fn) return FALSE;
    return fn(request, infoLevel, name, buffer, bufLen, index);
}

__declspec(dllexport)
BOOL WINAPI WinHttpQueryDataAvailable(HINTERNET request, LPDWORD available)
{
    int slot = fake_slot(request);
    if (slot >= 0) {
        DWORD remaining = 0;
        EnterCriticalSection(&g_lock);
        if (g_fakes[slot].h == request) remaining = (g_fake_len > g_fakes[slot].off) ? g_fake_len - g_fakes[slot].off : 0;
        LeaveCriticalSection(&g_lock);
        if (available) *available = remaining;
        probe_log("QDA(fake) avail=%lu", remaining);
        return TRUE;
    }
    fn_qavail fn = (fn_qavail)resolve("WinHttpQueryDataAvailable");
    if (!fn) return FALSE;
    return fn(request, available);
}

__declspec(dllexport)
BOOL WINAPI WinHttpReadData(HINTERNET request, LPVOID buffer, DWORD toRead, LPDWORD read)
{
    int slot = fake_slot(request);
    if (slot >= 0) {
        DWORD n = 0;
        EnterCriticalSection(&g_lock);
        if (g_fakes[slot].h == request) {
            DWORD remaining = (g_fake_len > g_fakes[slot].off) ? g_fake_len - g_fakes[slot].off : 0;
            n = toRead < remaining ? toRead : remaining;
            if (n && buffer) memcpy(buffer, g_fake_body + g_fakes[slot].off, n);
            g_fakes[slot].off += n;
            /* Do NOT free the slot when the body is exhausted: the game's read
             * loop calls ReadData again to reach EOF, and a freed slot would fall
             * through to the REAL handle and read Capcom's real 401 body (which
             * then gets parsed instead of ours). Keep the slot; serve 0 = clean
             * EOF forever on this handle. */
        }
        LeaveCriticalSection(&g_lock);
        if (read) *read = n;
        probe_log("RD(fake) served=%lu h=%p", n, request);
        /* Arm the exception-capture window: the game parses right after this. */
        g_veh_hits = 0;
        g_veh_deadline = GetTickCount64() + 8000;
        /* keycap: the /sign parse runs next, synchronously on THIS thread. Record
         * the thread and arm the extractor breakpoint here so we log its key
         * lookups (the response schema). Only on the first (non-empty) serve. */
        if (g_keycap && n && g_sign_tid == 0) {
            g_sign_tid = GetCurrentThreadId();
            arm_keycap_current();
        }
        /* One-shot: dump decrypted sections for offline parser analysis. */
        if (g_dump_now && InterlockedExchange(&g_dumped, 1) == 0)
            CloseHandle(CreateThread(NULL, 0, dump_worker, NULL, 0, NULL));
        /* Trap the parse address on this thread; the game parses next, in-line. */
        if (g_hwbp) arm_hwbp();
        /* Data-breakpoint the served buffer to find who reads it (the real parser). */
        if (g_databp && buffer && n && InterlockedExchange((LONG *)&g_databp_addr_armed, 1) == 0) {
            g_databp_addr = buffer;
            arm_all_threads();
            probe_log("DATABP set on body buffer %p (%lu bytes)", buffer, n);
        }
        return TRUE;
    }

    fn_read fn = (fn_read)resolve("WinHttpReadData");
    if (!fn) return FALSE;
    BOOL ok = fn(request, buffer, toRead, read);
    char label[320]; recall(request, label, sizeof label);
    if (ok && read && *read && should_capture(label)) {
        probe_log("RD(real) served=%lu h=%p [%s]", *read, request, label);
        log_bytes("RESP-BODY", label, buffer, *read);
    }
    return ok;
}

/* Read the session flags to confirm async vs sync WinHTTP. */
typedef HINTERNET (WINAPI *fn_wopen)(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
__declspec(dllexport)
HINTERNET WINAPI WinHttpOpen(LPCWSTR agent, DWORD accessType, LPCWSTR proxy, LPCWSTR bypass, DWORD flags)
{
    probe_log("WinHttpOpen flags=0x%lX %s", flags, (flags & 0x10000000) ? "(ASYNC)" : "(sync)");
    fn_wopen fn = (fn_wopen)resolve("WinHttpOpen");
    if (!fn) return NULL;
    return fn(agent, accessType, proxy, bypass, flags);
}

/* Capture the game's async status callback (confirms async mode + lets a correct
 * fake drive completions later). */
typedef WINHTTP_STATUS_CALLBACK (WINAPI *fn_setcb)(HINTERNET, WINHTTP_STATUS_CALLBACK, DWORD, DWORD_PTR);
__declspec(dllexport)
WINHTTP_STATUS_CALLBACK WINAPI WinHttpSetStatusCallback(HINTERNET h, WINHTTP_STATUS_CALLBACK cb, DWORD flags, DWORD_PTR reserved)
{
    g_app_cb = cb;
    probe_log("SetStatusCallback cb=%p flags=0x%lX", (void *)cb, flags);
    fn_setcb fn = (fn_setcb)resolve("WinHttpSetStatusCallback");
    if (!fn) return NULL;
    return fn(h, cb, flags, reserved);
}

/* ─── entry ───────────────────────────────────────────────────────────── */

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID reserved)
{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        if (InterlockedCompareExchange(&g_lock_ready, 1, 0) == 0)
            InitializeCriticalSection(&g_lock);
        DisableThreadLibraryCalls(inst);
        AddVectoredExceptionHandler(1, cpp_exc_veh);
        probe_log("---- attach: WinHTTP probe active ----");
    }
    return TRUE;
}
