<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>FakePhoton.Standard</AssemblyName>
    <RootNamespace>FakePhoton.Standard</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS0649</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../abstractions/FakePhoton.Abstractions.csproj" />
  </ItemGroup>
</Project>
