/**
 * Build the PartyWin.dll replacement.
 *
 * Every export of Microsoft's PartyWin.dll must exist in ours, because the game
 * links it statically: one missing name is a process that dies before its entry
 * point. The 48 functions the game imports are implemented in shim.cpp; the rest
 * of the real export table is pointed at PartyShimUnsupported so the surface is
 * identical either way. exports.h is generated from the real DLL's export table.
 *
 * "It linked" proves nothing about that, so the built table is read back and
 * compared name by name.
 *
 * Usage: node build.js <real PartyWin.dll> [outDir]
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { readExports } = require('../../tools/peExports');

const VCVARS = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat';

function implementedNames(source) {
  const names = new Set();
  const re = /^PartyError PARTY_API (Party\w+)\(/gm;
  let m;
  while ((m = re.exec(source))) if (m[1] !== 'PartyShimUnsupported') names.add(m[1]);
  return names;
}

function build(realDll, outDir) {
  if (!fs.existsSync(realDll)) throw new Error(`real PartyWin.dll not found: ${realDll}`);
  const vcvars = [process.env.LIBRARIAN_VCVARS, VCVARS].filter(Boolean).find(p => fs.existsSync(p));
  if (!vcvars) throw new Error('vcvars64.bat not found (set LIBRARIAN_VCVARS)');
  fs.mkdirSync(outDir, { recursive: true });

  const source = fs.readFileSync(path.join(__dirname, 'shim.cpp'), 'utf8');
  const implemented = implementedNames(source);
  const real = readExports(realDll).exports.map(e => e.name);
  const stray = [...implemented].filter(n => !real.includes(n));
  if (stray.length) throw new Error(`shim implements names PartyWin does not export: ${stray.join(', ')}`);

  const lines = ['/* Generated by build.js from the real PartyWin.dll export table. */'];
  for (const name of real) {
    lines.push(implemented.has(name)
      ? `#pragma comment(linker, "/EXPORT:${name}")`
      : `#pragma comment(linker, "/EXPORT:${name}=PartyShimUnsupported")`);
  }
  fs.writeFileSync(path.join(outDir, 'exports.h'), lines.join('\n') + '\n');

  const win = p => path.resolve(p).replace(/\//g, '\\');
  const outDll = path.join(outDir, 'PartyWin.dll');
  const batPath = path.join(outDir, 'build.bat');
  fs.writeFileSync(batPath, [
    '@echo off',
    `call "${win(vcvars)}" >nul || exit /b 1`,
    [
      'cl /nologo /LD /MT /O2 /W3 /EHsc /std:c++17 /D_CRT_SECURE_NO_WARNINGS',
      `/I"${win(outDir)}" /I"${win(path.join(__dirname, 'vendor'))}"`,
      `"${win(path.join(__dirname, 'shim.cpp'))}"`,
      `/Fo"${win(outDir)}\\\\"`,
      `/Fe"${win(outDll)}"`,
      '/link', '/OPT:NOREF',
    ].join(' '),
    'exit /b %ERRORLEVEL%',
  ].join('\r\n') + '\r\n');

  let output = '';
  try {
    output = execFileSync('cmd.exe', ['/c', win(batPath)], { cwd: outDir, encoding: 'utf8' });
  } catch (e) {
    throw new Error(`compile failed:\n${e.stdout || ''}${e.stderr || ''}`);
  }

  const built = readExports(outDll).exports.map(e => e.name);
  const missing = real.filter(n => !built.includes(n));
  const extra = built.filter(n => !real.includes(n));
  if (missing.length || extra.length) {
    throw new Error(`export table differs from the real DLL: missing [${missing.join(', ')}] extra [${extra.join(', ')}]`);
  }
  return { outDll, exports: built.length, implemented: implemented.size, unsupported: built.length - implemented.size, compilerOutput: output };
}

module.exports = { build, implementedNames };

if (require.main === module) {
  const [realDll, outDir = path.join(__dirname, 'out')] = process.argv.slice(2);
  if (!realDll) { console.error('usage: node build.js <real PartyWin.dll> [outDir]'); process.exit(1); }
  const r = build(realDll, outDir);
  console.log(`${r.outDll}: ${r.exports} exports (${r.implemented} implemented, ${r.unsupported} unsupported)`);
}
