/*
 * PlayFab Party probe — read-only instrumentation of PartyWin.dll.
 *
 * Monster Hunter Wilds does not run its sessions over Steam. PartyWin.dll is
 * Microsoft's PlayFab Party SDK, and the game's own code calls the data half of
 * it (PartyCreateNewNetwork, PartyNetworkGetEndpoints, PartyEndpointSendMessage)
 * rather than only the voice half. So Steam lobbies and P2P — the thing
 * Librarian's online mode supplies — are not what carries a hunt.
 *
 * That leaves one question worth answering before anything is built: Party's
 * documented join flow has the host serialize a *network descriptor* to a
 * printable string and hand it to an out-of-band channel of the title's
 * choosing. The joiner deserializes that string and connects. Which channel
 * Capcom chose decides everything downstream:
 *
 *   · a Steam lobby  — gbe_fork already emulates lobbies and their data, so two
 *                      instances could exchange it without Capcom in the loop
 *   · Capcom's own session service — it cannot, and that is a very different
 *                      and much larger problem
 *
 * This file answers that by logging the string at both ends. It changes no
 * behaviour: every call is passed through to the genuine library untouched, and
 * every export this DLL does not implement is a loader forwarder to it.
 *
 * The genuine PartyWin.dll must be renamed PartyWin_o.dll beside this one.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>

/* Generated by generate.js: one /EXPORT: forwarder per name we do not implement. */
#include "forwards.h"

#define ORIGINAL_DLL   L"PartyWin_o.dll"
#define LOG_NAME       "librarian_party.log"

/* Party returns PartyError, a 32-bit code; 0 is success. */
typedef unsigned int PartyError;

/*
 * A thunk takes four register arguments and forwards all four.
 *
 * On x64 there is one calling convention and the first four arguments live in
 * registers, so passing four along is correct for any function that takes four
 * or fewer — extra registers are simply ignored by the callee. It is *not*
 * correct for a function with stack arguments, which is why generate.js keeps
 * the implemented list to signatures that were checked against the Party C API.
 */
typedef PartyError (*PartyFn4)(void *, void *, void *, void *);

static HMODULE g_original;
static CRITICAL_SECTION g_lock;
static volatile LONG g_lock_ready;
static char g_log_path[MAX_PATH];

/* ─── logging ─────────────────────────────────────────────────────────── */

/* The log sits beside this DLL, which is the game folder. */
static const char *log_path(void)
{
    if (g_log_path[0]) return g_log_path;

    char dir[MAX_PATH];
    HMODULE self = NULL;
    GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                       GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                       (LPCWSTR)(void *)&log_path, &self);
    DWORD n = GetModuleFileNameA(self, dir, sizeof dir);
    if (n == 0 || n >= sizeof dir) return NULL;
    char *slash = strrchr(dir, '\\');
    if (!slash) return NULL;
    *(slash + 1) = '\0';
    if (strlen(dir) + strlen(LOG_NAME) >= sizeof g_log_path) return NULL;
    strcpy(g_log_path, dir);
    strcat(g_log_path, LOG_NAME);
    return g_log_path;
}

static void probe_log(const char *fmt, ...)
{
    const char *path = log_path();
    if (!path) return;

    EnterCriticalSection(&g_lock);
    FILE *f = fopen(path, "a");
    if (f) {
        SYSTEMTIME t;
        GetLocalTime(&t);
        fprintf(f, "[%02u:%02u:%02u.%03u] ", t.wHour, t.wMinute, t.wSecond, t.wMilliseconds);
        va_list ap;
        va_start(ap, fmt);
        vfprintf(f, fmt, ap);
        va_end(ap);
        fputc('\n', f);
        fclose(f);
    }
    LeaveCriticalSection(&g_lock);
}

/*
 * Only log a pointer as text when it really is text.
 *
 * Which argument holds the string is inferred from the documented signature,
 * and a wrong guess would otherwise dump raw memory into the log or read off
 * the end of a buffer. Requiring printable ASCII and a terminator inside the
 * cap makes a bad guess show up as "(not a string)" instead.
 */
static int printable(const void *p, size_t cap)
{
    if (!p) return 0;
    const unsigned char *s = (const unsigned char *)p;
    if (IsBadReadPtr(p, 1)) return 0;
    for (size_t i = 0; i < cap; i++) {
        if (IsBadReadPtr(s + i, 1)) return 0;
        if (s[i] == '\0') return i > 0;
        if (s[i] < 0x20 || s[i] > 0x7e) return 0;
    }
    return 0;
}

/* ─── forwarding ──────────────────────────────────────────────────────── */

/*
 * Resolve against the genuine library.
 *
 * The forwarded exports make the loader map PartyWin_o.dll at process start, so
 * by the time any thunk runs it is already present and GetModuleHandle answers.
 * LoadLibrary is the fallback for the case where every call into this DLL
 * happened to be an implemented one; it is safe here because a thunk runs long
 * after DllMain, never under the loader lock.
 */
static PartyFn4 resolve(const char *name)
{
    if (!g_original) {
        HMODULE h = GetModuleHandleW(ORIGINAL_DLL);
        if (!h) h = LoadLibraryW(ORIGINAL_DLL);
        if (!h) {
            probe_log("FATAL: cannot load %ls — is the genuine DLL renamed?", ORIGINAL_DLL);
            return NULL;
        }
        g_original = h;
    }
    PartyFn4 fn = (PartyFn4)(void *)GetProcAddress(g_original, name);
    if (!fn) probe_log("FATAL: %s missing from %ls", name, ORIGINAL_DLL);
    return fn;
}

/* ─── the three instrumented calls ────────────────────────────────────── */

/*
 * PartyInitialize(handle, titleId)
 *
 * Logged for the PlayFab title id, which names the backend the game
 * authenticates against, and to mark where in the startup sequence Party wakes
 * up. Both arguments are tested for text because the C wrapper's handle
 * placement is not worth guessing at.
 */
__declspec(dllexport) PartyError PartyInitialize(void *a, void *b, void *c, void *d)
{
    if (printable(b, 128))      probe_log("PartyInitialize titleId=\"%s\"", (const char *)b);
    else if (printable(a, 128)) probe_log("PartyInitialize titleId=\"%s\"", (const char *)a);
    else                        probe_log("PartyInitialize (title id not in a register arg)");

    PartyFn4 fn = resolve("PartyInitialize");
    if (!fn) return (PartyError)-1;
    PartyError r = fn(a, b, c, d);
    probe_log("PartyInitialize -> %u", r);
    return r;
}

/*
 * PartySerializeNetworkDescriptor(descriptor, outString)
 *
 * The host side. The buffer is only filled once the real call returns, so the
 * log happens afterwards. This string is the thing the game must hand to
 * another player somehow — whatever carries it next is the answer.
 */
__declspec(dllexport) PartyError PartySerializeNetworkDescriptor(void *a, void *b, void *c, void *d)
{
    PartyFn4 fn = resolve("PartySerializeNetworkDescriptor");
    if (!fn) return (PartyError)-1;
    PartyError r = fn(a, b, c, d);

    /* c_maxSerializedNetworkDescriptorStringLength is 448; allow for the nul. */
    if (r == 0 && printable(b, 449)) probe_log("SERIALIZE -> \"%s\"", (const char *)b);
    else if (r == 0)                 probe_log("SERIALIZE -> (not a string in arg 2), err=%u", r);
    else                             probe_log("SERIALIZE failed err=%u", r);
    return r;
}

/*
 * PartyDeserializeNetworkDescriptor(inString, descriptor)
 *
 * The joining side, and the more informative of the two: a string arriving here
 * has already travelled the channel we are trying to name. Logged before the
 * call, so it is captured even if the descriptor is stale and the call fails.
 */
__declspec(dllexport) PartyError PartyDeserializeNetworkDescriptor(void *a, void *b, void *c, void *d)
{
    if (printable(a, 449)) probe_log("DESERIALIZE <- \"%s\"", (const char *)a);
    else                   probe_log("DESERIALIZE <- (not a string in arg 1)");

    PartyFn4 fn = resolve("PartyDeserializeNetworkDescriptor");
    if (!fn) return (PartyError)-1;
    PartyError r = fn(a, b, c, d);
    probe_log("DESERIALIZE -> %u", r);
    return r;
}

/* ─── entry ───────────────────────────────────────────────────────────── */

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID reserved)
{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        /*
         * Nothing that touches the loader belongs here. The critical section is
         * the one thing set up eagerly, because a thunk can run before any
         * other initialisation and two of them can race on the log file.
         */
        if (InterlockedCompareExchange(&g_lock_ready, 1, 0) == 0)
            InitializeCriticalSection(&g_lock);
        DisableThreadLibraryCalls(inst);
        probe_log("---- attach: PartyWin probe active ----");
    }
    return TRUE;
}
